---
- name: 'Install dependencies'
  tags: 'nodejs'
  sudo: 'yes'
  apt: >
    pkg={{ item }}
    update-cache=yes
  with_items:
    - 'git'

- name: 'Add Node.js PPA'
  tags: 'nodejs'
  sudo: 'yes'
  apt_repository: >
    repo=ppa:chris-lea/node.js
    state=present

- name: 'Install Node.js'
  tags: 'nodejs'
  sudo: 'yes'
  apt: pkg=nodejs

- name: 'Install npm global packages'
  tags:
    - 'nodejs'
    - 'npm'
  sudo: 'yes'
  npm: >
    name={{ item }}
    state=present
    global=yes
    registry=http://registry.npmjs.org
  with_items: nodejs_global_packages

- name: 'Install local npm packages'
  sudo: 'no'
  tags:
    - 'nodejs'
    - 'npm'
  npm: 'path={{ nodejs_app_root }}'
  when: 'nodejs_app_root is defined'

- name: 'Ensure bower is installed'
  tags:
    - 'nodejs'
    - 'bower'
  sudo: 'yes'
  npm: >
    name=bower
    state=present
    global=yes
    registry=https://registry.npmjs.org
  when: 'nodejs_do_bower_install == true and nodejs_app_root is defined'

- name: 'Install local bower packages'
  tags:
    - 'nodejs'
    - 'bower'
  sudo: 'no'
  remote_user: '{{ nodejs_user }}'
  command: 'bower install chdir={{ nodejs_app_root }}'
  when: 'nodejs_do_bower_install == true and nodejs_app_root is defined'