---
- name: 'Add Node.js PPA'
  tags: 'nodejs'
  sudo: 'yes'
  apt_repository: >
    repo=ppa:chris-lea/node.js
    state=present

- name: 'Install Node.js'
  tags: 'nodejs'
  sudo: 'yes'
  apt: >
    pkg=nodejs
    update-cache=yes

- name: 'Install npm global packages'
  tags: 'nodejs'
  sudo: 'yes'
  npm: >
    name={{ item }}
    state=present
    global=yes
    registry=http://registry.npmjs.org
  with_items: nodejs_global_packages

- name: 'Install local npm packages'
  tags: 'nodejs'
  npm: 'path={{ nodejs_app_root }}'
  when: 'nodejs_app_root is defined'

- name: 'Ensure bower is installed'
  tags: 'nodejs'
  sudo: 'yes'
  npm: >
    name=bower
    state=present
    global=yes
    registry=https://registry.npmjs.org
  when: 'nodejs_do_bower_install == true and nodejs_app_root is defined' 

- name: 'Install local bower packages'
  tags: 'nodejs'
  command: 'bower install chdir={{ nodejs_app_root }}'
  when: 'nodejs_do_bower_install == true and nodejs_app_root is defined' 